# Generated by Django 4.0 on 2022-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('port', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=30)),
                ('gamemode', models.CharField(choices=[('RT', 'Retake'), ('DM', 'Deathmatch'), ('EX', 'Execute'), ('SU', 'Surf'), ('KZ', 'Kz'), ('OT', 'Other')], default='OT', max_length=2)),
            ],
        ),
    ]
