# Generated by Django 4.0 on 2022-01-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeServ', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('ip', 'port')},
        ),
    ]
