# Generated by Django 4.0 on 2022-01-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeServ', '0002_alter_server_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(),
        ),
    ]
